import { writeFileSync } from "node:fs";
import type { BranchReportEntry } from "./classify.js";

/**
 * SAFETY: this module never executes any git command. It only ever
 * produces shell script TEXT (generateDeleteScript) or writes that text
 * to a file (writeDeleteScript). No code path in this package calls
 * `git branch -d/-D` or `git push origin --delete` for real - review
 * and run the generated script yourself.
 */

function formatBranchComment(branch: BranchReportEntry): string {
  const mergedLabel = branch.merged ? "merged into main" : "NOT merged into main";
  const days = branch.daysSinceLastCommit.toFixed(1);
  return `# ${branch.name} - ${mergedLabel}, ${days} days since last commit`;
}

/**
 * Generates the text of a shell script that deletes the given (already
 * filtered to "stale") branches. Local branches get `git branch -d`
 * (safe delete, refuses unmerged branches - matches git's own default
 * safety behavior). Remote-tracking branches (isRemote: true, names of
 * the form "origin/<name>") get `git push origin --delete <name>` with
 * the "origin/" prefix stripped.
 */
export function generateDeleteScript(branches: BranchReportEntry[]): string {
  const lines: string[] = [];
  lines.push("#!/usr/bin/env bash");
  lines.push("set -euo pipefail");
  lines.push("");
  lines.push("# Generated by @kasap/stale-branch-cleaner.");
  lines.push("# Review every command below before running this script - nothing here");
  lines.push("# has been executed automatically.");
  lines.push("#");
  lines.push("# Local branches use `git branch -d`, which refuses to delete a branch");
  lines.push("# that is not fully merged. If you really want to force-delete an");
  lines.push("# unmerged local branch, manually change that line's `-d` to `-D`.");
  lines.push("");

  if (branches.length === 0) {
    lines.push("# No stale branches found - nothing to delete.");
    lines.push("");
    return lines.join("\n");
  }

  for (const branch of branches) {
    lines.push(formatBranchComment(branch));
    if (branch.isRemote) {
      const localName = branch.name.startsWith("origin/") ? branch.name.slice("origin/".length) : branch.name;
      lines.push(`git push origin --delete ${localName}`);
    } else {
      lines.push(`git branch -d ${branch.name}`);
    }
    lines.push("");
  }

  return lines.join("\n");
}

/**
 * Writes the generated delete script to disk. This is the only place
 * in the package that touches the filesystem for the delete script -
 * it still never executes any git command itself.
 */
export function writeDeleteScript(path: string, branches: BranchReportEntry[]): void {
  const content = generateDeleteScript(branches);
  writeFileSync(path, content, { encoding: "utf8", mode: 0o755 });
}
